name: medusa-plugin-whatsapp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [16.x]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-verion }}
      - name: 'install prism'
        run: |
          yarn global add @stoplight/prism-cli
          prism mock https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json
      - name: 'yarn install'
        #working-directory: ./
        run: yarn
      - name: 'run build'
        #working-directory: ./
        run: yarn run build  
      - name: 'run unit tests'
        working-directory: ../medusa-plugin-whatsapp
        run: yarn run test